"""
Embedded Blank character template for "Generate new Character".
"""
from __future__ import annotations

import base64

# Base64-encoded Blank character (1003 bytes).
TEMPLATE_BYTES = base64.b64decode(
    "VapVqmkAAADrAwAAjW6M7wAAAAAAAAAAAhAeAQAAAABJYptp////////AAD//wAA//8AAP//AAD/"
    "/wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAAAAAAARgAAAAAA"
    "AAAAAAAA//////8J//////////////////////////////////+AAACmPysNAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAADAAB3bmQg/wIAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAABCcnV0dXMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAFdvbyEGAAAAKgEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAABXUwEAAABQAAIBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAIBAQAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAIBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAF3NAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABnZgAeCJCBgAwGPGAAoAUcAGgBCAAy"
    "QAKADKAA4AksAHgCDAL/AWlmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASk0HABAgogAV"
    "AADPTwAQIKIAFQQAz08AECCiABUIAM9PABAgogAVDADPTwAQIKIABeTEkAgQIKIABaTkRyIAECCC"
    "AA0RALBjaK8H8AgIHh5YYyT/AUpNAABqZmtmAAEAbGYAAA=="
)
